# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3855bce4a2cc91de03e68b798f90a3e8fb1fdc093508b34ec29864edf21e642b1cae189d68dad99cad22ecae7d4ec9196ce26765d2e7375916a6a554a34a18ba

test:
  secret_key_base: 91397f71fd07b45347b416f8bddf414242a685b4b7d23c6fc9ce70356643f0b96a9a513c6ec985d0c1e487caa8e937cad25cb084c0e64c9f5fe3e8f94de89733

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
